// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/statistics.proto

package statisticspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOrderStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrderStatisticsRequest) Reset() {
	*x = UserOrderStatisticsRequest{}
	mi := &file_proto_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderStatisticsRequest) ProtoMessage() {}

func (x *UserOrderStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderStatisticsRequest.ProtoReflect.Descriptor instead.
func (*UserOrderStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *UserOrderStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserOrderStatisticsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalOrders    int32                  `protobuf:"varint,2,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	MostActiveHour string                 `protobuf:"bytes,3,opt,name=most_active_hour,json=mostActiveHour,proto3" json:"most_active_hour,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserOrderStatisticsResponse) Reset() {
	*x = UserOrderStatisticsResponse{}
	mi := &file_proto_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderStatisticsResponse) ProtoMessage() {}

func (x *UserOrderStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserOrderStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *UserOrderStatisticsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserOrderStatisticsResponse) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *UserOrderStatisticsResponse) GetMostActiveHour() string {
	if x != nil {
		return x.MostActiveHour
	}
	return ""
}

type UserStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatisticsRequest) Reset() {
	*x = UserStatisticsRequest{}
	mi := &file_proto_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatisticsRequest) ProtoMessage() {}

func (x *UserStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatisticsRequest.ProtoReflect.Descriptor instead.
func (*UserStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *UserStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserStatisticsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RegistrationDate  string                 `protobuf:"bytes,2,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	TotalOrders       int32                  `protobuf:"varint,3,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	AverageOrderValue float32                `protobuf:"fixed32,4,opt,name=average_order_value,json=averageOrderValue,proto3" json:"average_order_value,omitempty"`
	TotalSpent        float32                `protobuf:"fixed32,5,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"` // Added field for total spent by user
	PeakHour          string                 `protobuf:"bytes,6,opt,name=peak_hour,json=peakHour,proto3" json:"peak_hour,omitempty"`         // Added field for user's peak hour
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserStatisticsResponse) Reset() {
	*x = UserStatisticsResponse{}
	mi := &file_proto_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatisticsResponse) ProtoMessage() {}

func (x *UserStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *UserStatisticsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStatisticsResponse) GetRegistrationDate() string {
	if x != nil {
		return x.RegistrationDate
	}
	return ""
}

func (x *UserStatisticsResponse) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *UserStatisticsResponse) GetAverageOrderValue() float32 {
	if x != nil {
		return x.AverageOrderValue
	}
	return 0
}

func (x *UserStatisticsResponse) GetTotalSpent() float32 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

func (x *UserStatisticsResponse) GetPeakHour() string {
	if x != nil {
		return x.PeakHour
	}
	return ""
}

var File_proto_statistics_proto protoreflect.FileDescriptor

const file_proto_statistics_proto_rawDesc = "" +
	"\n" +
	"\x16proto/statistics.proto\x12\fstatisticspb\"5\n" +
	"\x1aUserOrderStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x83\x01\n" +
	"\x1bUserOrderStatisticsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\ftotal_orders\x18\x02 \x01(\x05R\vtotalOrders\x12(\n" +
	"\x10most_active_hour\x18\x03 \x01(\tR\x0emostActiveHour\"0\n" +
	"\x15UserStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xef\x01\n" +
	"\x16UserStatisticsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11registration_date\x18\x02 \x01(\tR\x10registrationDate\x12!\n" +
	"\ftotal_orders\x18\x03 \x01(\x05R\vtotalOrders\x12.\n" +
	"\x13average_order_value\x18\x04 \x01(\x02R\x11averageOrderValue\x12\x1f\n" +
	"\vtotal_spent\x18\x05 \x01(\x02R\n" +
	"totalSpent\x12\x1b\n" +
	"\tpeak_hour\x18\x06 \x01(\tR\bpeakHour2\xe3\x01\n" +
	"\x11StatisticsService\x12n\n" +
	"\x17GetUserOrdersStatistics\x12(.statisticspb.UserOrderStatisticsRequest\x1a).statisticspb.UserOrderStatisticsResponse\x12^\n" +
	"\x11GetUserStatistics\x12#.statisticspb.UserStatisticsRequest\x1a$.statisticspb.UserStatisticsResponseB\x14Z\x12proto/statisticspbb\x06proto3"

var (
	file_proto_statistics_proto_rawDescOnce sync.Once
	file_proto_statistics_proto_rawDescData []byte
)

func file_proto_statistics_proto_rawDescGZIP() []byte {
	file_proto_statistics_proto_rawDescOnce.Do(func() {
		file_proto_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_statistics_proto_rawDesc), len(file_proto_statistics_proto_rawDesc)))
	})
	return file_proto_statistics_proto_rawDescData
}

var file_proto_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_statistics_proto_goTypes = []any{
	(*UserOrderStatisticsRequest)(nil),  // 0: statisticspb.UserOrderStatisticsRequest
	(*UserOrderStatisticsResponse)(nil), // 1: statisticspb.UserOrderStatisticsResponse
	(*UserStatisticsRequest)(nil),       // 2: statisticspb.UserStatisticsRequest
	(*UserStatisticsResponse)(nil),      // 3: statisticspb.UserStatisticsResponse
}
var file_proto_statistics_proto_depIdxs = []int32{
	0, // 0: statisticspb.StatisticsService.GetUserOrdersStatistics:input_type -> statisticspb.UserOrderStatisticsRequest
	2, // 1: statisticspb.StatisticsService.GetUserStatistics:input_type -> statisticspb.UserStatisticsRequest
	1, // 2: statisticspb.StatisticsService.GetUserOrdersStatistics:output_type -> statisticspb.UserOrderStatisticsResponse
	3, // 3: statisticspb.StatisticsService.GetUserStatistics:output_type -> statisticspb.UserStatisticsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_statistics_proto_init() }
func file_proto_statistics_proto_init() {
	if File_proto_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_statistics_proto_rawDesc), len(file_proto_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_statistics_proto_goTypes,
		DependencyIndexes: file_proto_statistics_proto_depIdxs,
		MessageInfos:      file_proto_statistics_proto_msgTypes,
	}.Build()
	File_proto_statistics_proto = out.File
	file_proto_statistics_proto_goTypes = nil
	file_proto_statistics_proto_depIdxs = nil
}
